name: Mon premier workflow
on: push

jobs:
  testdocker:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
    steps:
      - name: install redis-cli
        run: apt update && apt install redis-tools -y
      - name: test connexion
        run: redis-cli -h redis ping
