name: Second workflow
on: [push]
env:
  VAR_1: ubuntu-latest

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  deploy:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - run: echo DEPLOY to production
