name: Vérifier le titre d'une PR
on: push

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Une étape !!
        run: |
          titre="${{ github.event.head_commit.message }}"
          echo hello
