name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo 123 > test.txt
          git add test.txt
          git commit -m "add test.txt"
          git push origin main
