name: my cache
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('./vite-project/package-lock.json') }}
          path: ./vite-project/.npm
      - run: ls -la ./vite-project
      # - name: install dependencies
      #   working-directory: ./vite-project
      #   run: npm ci --cache .npm --prefer-offline

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/cache@v3
  #       with:
  #         key: ${{ runner.os }}-${{ hashFiles('./vite-project/package-lock.json') }}
  #         path: ./vite-project/.npm
  #     - name: install dependencies
  #       working-directory: ./vite-project
  #       run: npm ci --cache .npm --prefer-offline
  #     - name: test
  #       run: echo test
