name: Second workflow
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - run: ls
      - run: cat onefile
      - run: cat test/anotherfile.txt
