name: Second workflow
on: push

jobs:
  exemple_set_output:
    runs-on: ubuntu-latest
    steps:
      - name: Définir un paramètre de sortie
        run: echo "::set-output name=fruit::pomme"
        id: step1
      - name: Utiliser le paramètre de sortie
        run: echo "Le fruit sélectionné est ${{ steps.step1.outputs.fruit }}"
