name: Second workflow
on: push

jobs:
  exemple_notice:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message de notification
        id: step1 
        run: echo ::set-output name=fruit::pomme


      - name: Afficher un message de notification
        if: steps.step1.outputs.fruit == 'poire'
        run: echo ::error::Erreur ici
   
