name: Second workflow
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo $SHELL
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo $SHELL
        shell: sh
      - run: echo $ENV:shell
        shell: pwsh
        
   
