name: Exemple d'utilisation de defaults

defaults:
  run:
    shell: bash
    working-directory: ./scripts

jobs:
  exemple_job:
    runs-on: ubuntu-latest
    steps:
    - name: Vérifier le répertoire de travail
      run: pwd # Doit afficher /github/workspace/scripts
    - name: Attendre pour visualiser
      run: sleep 5
