name: Second workflow
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $SHELL
          pwd
      - uses: actions/checkout@v4
      - working-directory: ./test
        run: |
          ls
          pwd
   
