name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 123 > test.txt
      - uses: actions/upload-artifact@v3
        with:
          name: myfirstartifact
          path: ./test.txt
          if-no-files-found: warn
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: myfirstartifact
          path: ./ici
      - run: |
          ls
          ls ./ici
          cat ./ici/test.txt
