name: Vérifier le titre d'une PR
on: push

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Une étape !!!!!!!
        env:
          TITLE: ${{ github.event.head_commit.message }}
        run: |
          titre=$TITLE
          echo hello
