name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -la
          npm -v
