name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '# TITRE' >> $GITHUB_STEP_SUMMARY
          echo 'il c est passé si et ça :rocket:' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '- [*] un' >> $GITHUB_STEP_SUMMARY
          echo '- [*] deux' >> $GITHUB_STEP_SUMMARY
          echo '- [*] trois' >> $GITHUB_STEP_SUMMARY
      # - run: |
      #     echo #JE SUIS UNE AUTRE STEP AVEC UN AUTRE TITRE >> $GITHUB_STEP_SUMMARY
      #     echo il c est passé si et ça >> $GITHUB_STEP_SUMMARY
