name: my cache
on: push

# simple matrix

# jobs:
# build:
#   runs-on: ubuntu-latest
#   strategy:
#     matrix:
#       os: [ubuntu-latest, window-latest, macos-latest]
#       v: [12, 13, 14]
#   steps:
#     - run: |
#         echo ${{ matrix.os }} : ${{ matrix.v }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         os: [ubuntu-latest, window-latest]
#         v: [12, 13]
#         include:
#           - key: value
#     steps:
#       - run: |
#           echo ${{ matrix.os }} : ${{ matrix.v }} : ${{ matrix.key }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         os: [ubuntu-latest, window-latest]
#         v: [12, 13]
#         include:
#           - os: ubuntu-latest
#             key: value
#     steps:
#       - run: |
#           echo ${{ matrix.os }} : ${{ matrix.v }} : ${{ matrix.key }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         os: [ubuntu-latest, window-latest]
#         v: [12, 13]
#         exclude:
#           - v: 12
#     steps:
#       - run: |
#           echo ${{ matrix.os }} : ${{ matrix.v }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cloud: ovh
            endpoint: ovh.com
          - cloud: aws
            endpoint: aws.com
    steps:
      - run: |
          echo ${{ matrix.cloud }} : ${{ matrix.endpoint }}
