name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: waitforme
    steps:
      - run: |
          echo Very long job
          sleep 100
          echo Done !
