name: Mon premier workflow
on: push

jobs:
  testdocker:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: install redis-cli
        run: sudo apt update && sudo apt install redis-tools -y
      - name: test connexion
        run: |
          sleep 5
          redis-cli -h localhost -p 6379 ping
