name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 123 > test.txt
      - uses: actions/upload-artifact
        with:
          name: myfirstartifact
          path: ./test.txt
          if-no-files-found: warn
          retention-days: 1

  # deploy:
  #   runs-on: ubuntu-latest
