name: Workflow staging
on:
  push:
    branches: staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://toto.fr
    steps:
      - run: echo DEPLOY IN STAGING ! ${{ vars.KEY_TEST }} ${{ secrets.URL }}
